config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :publications
  resources :comments, only: [:create]

  post '/new_user_reaction', to: 'reactions#new_user_reaction', as: 'new_user_reaction'
  
  # Defines the root path route ("/")
  root "publications#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
  # accepts_nested_attributes_for :comments

  Kinds = %w[like dislike].freeze
  KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta"}.freeze
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @comment = Comment.new
    @comments = @publication.comments
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:image, :title, :description, :user_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group py-2">
    <%= form.label :image, "Imagen", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.text_field :image, placeholder: "URL Imagen", class: "form-control" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :title, "Titulo", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.text_field :title, placeholder: "Titulo", class: "form-control" %>
  </div>

  <div class="input-group py-2">
    <%= form.label :description, "Descripción", class: "input-group-text", style: "background-color: #e3f2fd;" %>
    <%= form.text_area :description, placeholder: "Descripción", class: "form-control" %>
  </div>
  
  <div class="py-2">
    <% if action_name == "new" %>
      <%= form.submit "Guardar", class: "btn btn-success rounded-pill fw-semibold text-white" %>
    <% else %>
      <%= form.submit "Actualizar", class: "btn btn-success rounded-pill fw-semibold text-white" %>
    <% end %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>" class="col-4 py-2">
  <div class="card text-center border-success">
    <img src="<%= publication.image %>" style="height: 200px; object-fit: cover;">
    <div class="card-header d-flex justify-content-around">
      <% Publication::Kinds.each do |kind| %>
        <% if kind == 'like' %>
          <% if action_name == 'show' %>
            <%= button_to new_user_reaction_path(publication_id: @publication.id, kind: kind), method: :post, style: "all: unset; cursor: pointer"  do %>
              <i class="bi bi-hand-thumbs-up-fill text-success fs-5"></i>
              <%= publication.reactions.select { | publication | publication[:kind] == 'like' }.count %>
            <% end %>
          <% else %>
            <div>
              <i class="bi bi-hand-thumbs-up-fill text-success fs-5"></i>
              <%= publication.reactions.select { | publication | publication[:kind] == 'like' }.count %>
            </div>
          <% end %>
        <% else %>
          <% if action_name == 'show' %>
            <%= button_to new_user_reaction_path(publication_id: @publication.id, kind: kind), method: :post, style: "all: unset; cursor: pointer"  do %>
              <i class="bi bi-hand-thumbs-up-fill text-danger fs-5"></i>
              <%= publication.reactions.select { | publication | publication[:kind] == 'dislike' }.count %>
            <% end %>
          <% else %>
            <div>
              <i class="bi bi-hand-thumbs-up-fill text-danger fs-5"></i>
              <%= publication.reactions.select { | publication | publication[:kind] == 'dislike' }.count %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title fw-bold">
        <%= publication.title %>
      </h5>
      <p class="card-text fst-italic">
        <%= publication.description %>
      </p>
    </div>
    <div class="card-footer">
      <% if action_name == 'index' %>
        <%= link_to publication do %>
          <i class="bi bi-eye-fill text-primary fs-5"></i>
        <% end %>
      <% else %>
        <div class="d-flex justify-content-around">
          <%= link_to publications_path do %>
            <i class="bi bi-arrow-return-left text-secondary fs-5 px-1"></i>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.id == @publication.user_id %>
              <%= link_to edit_publication_path(publication) do %>
                <i class="bi bi-pencil-fill text-success fs-5 px-1"></i>
              <% end %>
              <%= button_to @publication, method: :delete, style: "all: unset; cursor: pointer" do %>
                <i class="bi bi-trash-fill text-danger fs-5 px-1"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<div class="d-flex align-items-center">
  <div class="col-1 px-0" style="width: 35px">
    <%= link_to publications_path do %>
      <i class="bi bi-arrow-return-left text-secondary fs-5"></i>
    <% end %>
  </div>
  <h1>Editar Publicación</h1>
</div>

<%= render "form", publication: @publication %>

app/views/publications/index.html.erb
<div class="toast align-items-center text-bg-success" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="d-flex">
    <div class="toast-body">
      <%= notice %>
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>

<div class="container">
  <div class="d-flex justify-content-between align-items-center my-3">
    <h1>Publicaciones</h1>
    <% if user_signed_in? %>
      <%= link_to "Nueva Publicación", new_publication_path, class: "btn btn-outline-success" %>
    <% end %>
  </div>
  <div id="publications">
    <div class="row">
      <% @publications.each do |publication| %>
        <%= render publication %>
      <% end %>
    </div>
  </div>
</div>

app/views/publications/new.html.erb
<div class="d-flex align-items-center">
  <div class="col-1 px-0" style="width: 35px">
    <%= link_to publications_path do %>
      <i class="bi bi-arrow-return-left text-secondary fs-5"></i>
    <% end %>
  </div>
  <h1>Nueva Publicación</h1>
</div>

<%= render "form", publication: @publication %>

app/views/publications/show.html.erb
<div class="toast align-items-center text-bg-success" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="d-flex">
    <div class="toast-body">
      <%= notice %>
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>

<div class="row">
  <%= render @publication %>

  <div class="col-8 py-2">
    <h5 class="fw-bold text-center">Comentarios</h5>
    <%= render "comments/comment" %>
    <div class="justify-content-center align-items-center pt-2">
      <%= render "comments/form" %>
    </div>
  </div>
  
</div>